// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC2-jZilCUTJYAfNiVMI_dGntkgo-OKoc',
    appId: '1:731452984391:web:1d1135bf6df77df3c93562',
    messagingSenderId: '731452984391',
    projectId: 'zymov2',
    authDomain: 'zymov2.firebaseapp.com',
    storageBucket: 'zymov2.firebasestorage.app',
    measurementId: 'G-B6120HJF6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNdV8drCE5XYYMAUDUQLd3bbwt6mCrfLA',
    appId: '1:731452984391:android:59d572252929964fc93562',
    messagingSenderId: '731452984391',
    projectId: 'zymov2',
    storageBucket: 'zymov2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUMDtCnlpE-DSo0tA2bLlrCE9xb8PIi-E',
    appId: '1:731452984391:ios:5cb22513c4e39c3ec93562',
    messagingSenderId: '731452984391',
    projectId: 'zymov2',
    storageBucket: 'zymov2.firebasestorage.app',
    iosBundleId: 'com.example.zymoInternship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUMDtCnlpE-DSo0tA2bLlrCE9xb8PIi-E',
    appId: '1:731452984391:ios:5cb22513c4e39c3ec93562',
    messagingSenderId: '731452984391',
    projectId: 'zymov2',
    storageBucket: 'zymov2.firebasestorage.app',
    iosBundleId: 'com.example.zymoInternship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC2-jZilCUTJYAfNiVMI_dGntkgo-OKoc',
    appId: '1:731452984391:web:71b738285f8fe21dc93562',
    messagingSenderId: '731452984391',
    projectId: 'zymov2',
    authDomain: 'zymov2.firebaseapp.com',
    storageBucket: 'zymov2.firebasestorage.app',
    measurementId: 'G-TDC013CJJ4',
  );
}
